### ISSUE TITLE
boot0 for STM32G070RB is not working

### ISSUE THREAD

**Issue by MadZoids** [olikraus/stm32g031#1]
Hi, I use the [https://github.com/olikraus/stm32g031/blob/main/enable_boot0/enable_boot0.hex](url) for STM32G070RB but it's still can't be access via UART after i flash the hex to the virgin board.
Is it possible that the option byte address is different between stm32g031 with stm32g070?

**Comment by olikraus** [comment]
FLASH base address, option bit locations and also the pass key are the same.

> it's still can't be access via UART after i flash the hex to the virgin board.

During reset: Did you apply a high level at your boot0 pin?

**Comment by MadZoids** [comment]
Yes, I'm sure i have apply it, I've test it on different MCU, some of the STM32G070RB is still problem, some of them is working great.
Thank you.

**Comment by olikraus** [comment]
hmm.... maybe you could upload & execute the hex also via SWD
